import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import ToastContainer from "@/shared/providers/ToastProvider";
import LoadingProvider from "@/shared/providers/LoadingProvider";

export const metadata: Metadata = {
  title: "cher1sh-next-app",
  description: "Generated by cher1sh-next-app",
};

const pretendard = localFont({
    src: "../shared/fonts/pretendard.woff2",
    variable: "--font-prendard",
    weight: "100 900",
    display: "swap",
  });

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="ko">
      <body className={`${pretendard.variable} antialiased`}>
        <ToastContainer />
        <LoadingProvider color="#6969FF" />
        {children}
      </body>
    </html>
  );
}

export default RootLayout